### PR TITLE
Java afdist

### PR DESCRIPTION
**Pull request by benjeffery**
Initial stab at a Java version - I've copied the style of the C++ version quite closely, and haven't done any perf analysis yet.

It is pretty slow:
```
   num_samples  num_sites       tool  user_time  sys_time  wall_time storage
1        10000     863998       zarr      21.83      0.05  21.897036     hdd
0        10000     863998  zarr_java      57.97      0.71  57.913951     HDD
```

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Super!

What Java Zarr lib are you using? Can you add a rule to the software makefile to download the jar (or whatever you need to do with Java)?

Can you try commenting out the genotype processing here and see what the performance is like? It's roughly half-and-half time spend in Zarr getting and decoding the chunks vs time spent processing the genotypes in other implementations.

**Comment by jeromekelleher** [comment]
> What Java Zarr lib are you using? Can you add a rule to the software makefile to download the jar (or whatever you need to do with Java)?

Ah, scratch that - it's in the maven build file.

**Comment by benjeffery** [comment]
> Can you add a rule to the software makefile

It's already in this PR - if you have maven installed everything else should just work.

**Comment by benjeffery** [comment]
> Can you try commenting out the genotype processing here and see what the performance is like? It's roughly half-and-half time spend in Zarr getting and decoding the chunks vs time spent processing the genotypes in other implementations.

57s for complete code
23s for just chunk loading

So pretty much inline with the others

**Comment by jeromekelleher** [comment]
Interesting. What does perf think the time is spent on? Is this calling into the same implementation of Blosc or is the a native Java version involved?

**Comment by benjeffery** [comment]
Screenshot from 2024-09-18 13-12-11

We're calling into a native libblosc, but not the same as the python one which is part of a CPython `.so`. A smaller fraction is in blosc calls than the python version.

**Comment by jeromekelleher** [comment]
OK, so Java is slow. :shrug:

Amazing stuff, thanks @benjeffery!

**Pull request merged**
